apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-sample-service
  namespace: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-sample-service
  template:
    metadata:
      labels:
        app: aks-sample-service
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      serviceAccountName: sampleapp-pod-reder
      containers:
      - name: aks-sample-service
        image: morimotodevacr.azurecr.io/aks-sample-service:v8
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: aks-sample-service
  namespace: sampleapp
spec:
  ports:
  - port: 80
  selector:
    app: aks-sample-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-sample-app
  namespace: sampleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aks-sample-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: aks-sample-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      serviceAccountName: sampleapp-pod-reder
      containers:
      - name: aks-sample-app
        imagePullPolicy: Always
        image: morimotodevacr.azurecr.io/aks-sample-app:v8
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: AKS_SAMPLE_APP_URL1
          value: "http://20.46.187.233:8080/aks-sample-service"  
        - name: AKS_SAMPLE_APP_URL2
          value: "http://10.0.154.28/aks-sample-service2"
        - name: AKS_SAMPLE_APP_URL3
          value: "http://10.0.154.28/aks-sample-service3"
---
apiVersion: v1
kind: Service
metadata:
  name: aks-sample-app
  namespace: sampleapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aks-sample-app