version: '3'
services:
  aks-sample-app:
    container_name: aks-sample-app
    image: aks-sample-app:v1
    ports:
      - "80:80"
#    environment:
#      - AKS_SAMPLE_APP_URL1=http://aks-sample-service:8081/aks-sample-service
#      - AKS_SAMPLE_APP_URL2=http://aks-sample-service2:8082/aks-sample-service2
#      - AKS_SAMPLE_APP_URL3=http://aks-sample-service3:8083/aks-sample-service3
  aks-sample-service:
    container_name: aks-sample-service
    image: aks-sample-service:v1
#    environment:
#      - PORT=8081
  aks-sample-service2:
    container_name: aks-sample-service2
    image: aks-sample-service2:v1
#    environment:
#      - PORT=8082
  aks-sample-service3:
    container_name: aks-sample-service3
    image: aks-sample-service3:v1
#    environment:
#      - PORT=8083
