apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sampleapp
  name: pod-reader
rules:
- apiGroups: ["","extensions","apps"]
  resources: ["deployments","replicasets","pods","services","endpoints"]
  verbs: ["get","watch","list"]