apiVersion: v1
kind: ServiceAccount
metadata:
  name: sampleapp-pod-reder
  namespace: sampleapp
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reder-rolebinding
  namespace: sampleapp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reder
subjects:
  - kind: ServiceAccount
    name: sampleapp-pod-reder